[build]
  command = "npx clear-npm-cache && npm install -g npm@7 && npm install --force --legacy-peer-deps && npm run build"
  publish = "build-directory"  # Replace with the actual build output directory

[context.production.environment]
  NODE_VERSION = "14"  # Replace with the desired Node.js version

[context.branch-deploy.environment]
  NODE_VERSION = "14"  # Replace with the desired Node.js version
