[build]
  command = "npm cache clean -f && npm install -g npm@latest && npm install --force --legacy-peer-deps && npm run build"
  publish = "build-directory"  # Replace with the actual build output directory

[context.production.environment]
  NODE_VERSION = "14"  # Replace with the desired Node.js version

[context.branch-deploy.environment]
  NODE_VERSION = "14"  # Replace with the desired Node.js version

